# -*- coding: utf-8 -*-
"""Test1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Je-lNhgt2FMIo0JKau-b0eWR4KIO7PPb
"""

a=1
b=2
c=a+b
print(c*c)
print(a*a)
